### ISSUE TITLE
"Read More" link missing

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#112]
On the home page, the "read more" link to view the full single post is missing. You can open by clicking on the title of the post. Wasn't sure if this was an intentional change in format. Think this is intuitive enough that there's more content to expand without some marker for "read more" or "..."?

**Comment by dsifford** [comment]
Took that out on purpose because I didn't see a value in keeping it. Clicking the title of the post does the same thing as clicking the read more button. More importantly, if the post author accidentally inserts line breaks before the read more line, then those line breaks will show up in and cause the post snippet to look strange.

I can add back if you've got strong feelings about it, but IMHO, there is not one post that exists in the history of ALiEM that does not have either more content or more value (comments, etc) beyond what is visible in the post feed snippet.

**Comment by michellealiem** [comment]
Got it. Just wanted to make sure that it wasn't a bug. Thanks.
