### ISSUE TITLE
Youtube embed expansion stopped working

### ISSUE THREAD

**Issue by dsifford** [aliemteam/ALiEM#115]
Need to fix and then make sure that the youtube links are converted on this post: https://www.aliem.com/wp-admin/post.php?post=53828&action=edit

**Comment by michellealiem** [comment]
Is this something that I can fix, are you saying the you (Derek) need to
fix?


On February 16, 2018 at 10:31:58 AM, Derek Sifford (notifications@github.com)
wrote:

Need to fix and then make sure that the youtube links are converted on this
post: https://www.aliem.com/wp-admin/post.php?post=53828&action=edit

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aliemteam/ALiEM/issues/115>, or mute the thread

**Comment by dsifford** [comment]
@michellealiem Not sure what the issue is. 

The notes in the initial message are just to provide context and background to the issue in case I forget (or in case someone else wants to try and tackle).
